# Generated by Django 3.0.2 on 2020-05-05 11:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(verbose_name=uuid.uuid4)),
                ('real_name', models.CharField(max_length=100)),
                ('time_zone', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'api_member',
            },
        ),
        migrations.CreateModel(
            name='ActivityPeriods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_periods_api.Member')),
            ],
            options={
                'db_table': 'api_activity_period',
            },
        ),
    ]
