# Generated by Django 3.0.2 on 2020-05-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_periods_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityPeriods',
            new_name='ActivityPeriod',
        ),
    ]
