# Generated by Django 3.0.2 on 2020-05-05 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_periods_api', '0002_auto_20200505_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='activity_periods_api.Member'),
        ),
    ]
